openapi: 3.0.0
info:
  title: Product API
  description: API for managing products
  version: 1.0.0
paths:
  /api/products:
    get:
      summary: Get list of products
      responses:
        '200':
          description: List of products
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Product'
    post:
      summary: Create a product
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Product'
        required: true
      responses:
        '201':
          description: Product created
  /api/products/{id}:
    get:
      summary: Get a single product
      parameters:
        - name: id
          in: path
          required: true
          description: Product ID
          schema:
            type: integer
      responses:
        '200':
          description: Product details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'
        '404':
          description: Product not found
    put:
      summary: Update a product
      parameters:
        - name: id
          in: path
          required: true
          description: Product ID
          schema:
            type: integer
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Product'
        required: true
      responses:
        '200':
          description: Product updated
        '404':
          description: Product not found
    delete:
      summary: Delete a product
      parameters:
        - name: id
          in: path
          required: true
          description: Product ID
          schema:
            type: integer
      responses:
        '204':
          description: Product deleted
        '404':
          description: Product not found
components:
  schemas:
    Product:
      type: object
      properties:
        code:
          type: integer
          description: Product code
        status:
          type: string
          description: Product status
        imported_t:
          type: string
          format: date-time
          description: Import timestamp
        url:
          type: string
          description: Product URL
        product_name:
          type: string
          description: Product name
        quantity:
          type: string
          description: Quantity
        brands:
          type: string
          description: Brands
        categories:
          type: string
          description: Categories
        labels:
          type: string
          description: Labels
        cities:
          type: string
          description: Cities
        purchase_places:
          type: string
          description: Purchase places
        stores:
          type: string
          description: Stores
        ingredients_text:
          type: string
          description: Ingredients text
        traces:
          type: string
          description: Traces
        serving_size:
          type: string
          description: Serving size
        serving_quantity:
          type: number
          format: float
          description: Serving quantity
        nutriscore_score:
          type: integer
          description: Nutriscore score
        nutriscore_grade:
          type: string
          description: Nutriscore grade
        main_category:
          type: string
          description: Main category
        image_url:
          type: string
          description: Image URL
