services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: laravel_app
        restart: unless-stopped
        volumes:
            - .:/var/www
            - /var/www/vendor/
        networks:
            - app_network

    nginx:
        image: nginx:alpine
        container_name: nginx
        restart: unless-stopped
        ports:
            - "80:80"
        volumes:
            - .:/var/www
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        networks:
            - app_network

    mongo:
        container_name: mongo
        image: mongo:latest
        ports:
            - '27017:27017'
        volumes:
            - mongo_data:/data/db
            - ./init-replica-set.js:/docker-entrypoint-initdb.d/init-replica-set.js
        command: --replSet rs0
        networks:
            - app_network

volumes:
    mongo_data:
        driver: local

networks:
    app_network:
        driver: bridge
